travis:
  secure:
    BINSTAR_TOKEN: O2TCWXV9/TX3emOkSyLF/8jfBaormuV5/Wyxs9Yr3gKvHcB4zGyPNl1AHbmlMR7WyzQY91Id1ZLVoKbBw/0viHUn0NCnG1faKkCnkudOGtpMYophmFMtkIkeACRE9W+eVq6geEzYJxhTkTtUEiim1fexbbyMKKUJA9BZKOnt7eCnxKVt5f3Y2IRNrD4iusGnxQHmP48AGxsfGHxBkH7AYNc6O4D8N6TR3yKO6HzePxbMh/jlYi7ns8UvXO9Gd/Ah2jv/IlHn358kSO8u0qnyXK79K4VuRzLyVEpcM0FGb8HXPS4TKFBmJC+DZR/zfXAFKuWI3rwowe4h31NlbQjaXswcQb5dBaf4//TGcyESCly6d0OPMmFpsjlcqkNYW4TsO9md977ZmpO5W2h4gebLcIa9zpczdO+Xn3MQZoXZ/HW2fv+zFANTAgzJe+cjJ/SwBKXcbBew/WaOrGlKP0uJD98Ce3dR6Z2oTtsp4JGP0yyEy2ZJpOltVugOgRj8ze85PmxiMcpZPVTdHqkeZwX3p0PWb/20nZiahkW+BFvxjhTslsIxK32ofoSGPzv30Wk4HtxRZneHTBuOnItuOy4SUAsWrhI3E77HNydSl5L8X9iO++09az18rHInxcJi/n9bOQhGYD+9tte+9vypX4KOKwwkIx+wUtD+IdktRc0S44Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
